version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Prague"
    cooldown:
      default-days: 3
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
    reviewers:
      - "jan-kubica"

  - package-ecosystem: "bun"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Prague"
    cooldown:
      default-days: 3
    groups:
      oxc:
        patterns:
          - "oxlint"
          - "oxfmt"
      misc:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
    reviewers:
      - "jan-kubica"
