[package]
name = "stella-stdnum-napi"
version.workspace = true
edition.workspace = true
description = "Native bindings for Stella standard identifier validation"
license.workspace = true
publish.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = [
  "napi9",
] }
napi-derive = "3"
stella-stdnum-core = { path = "../stdnum-core" }

[dev-dependencies]
napi = { version = "3", default-features = false, features = [
  "dyn-symbols",
  "napi9",
] }

[build-dependencies]
napi-build = "2"

[lints]
workspace = true
