from typing import Literal

ErrorCode = Literal[
    "INVALID_FORMAT",
    "INVALID_LENGTH",
    "INVALID_CHECKSUM",
    "INVALID_COMPONENT",
]
EntityType = Literal["person", "company", "any"]
ValidatorScope = Literal["country", "global"]
CardNetwork = Literal[
    "visa",
    "mastercard",
    "amex",
    "discover",
    "diners",
    "jcb",
    "unionpay",
    "maestro",
]


class ValidationError:
    @property
    def code(self) -> ErrorCode: ...

    @property
    def message(self) -> str: ...


class ValidationResult:
    @property
    def valid(self) -> bool: ...

    @property
    def compact(self) -> str | None: ...

    @property
    def error(self) -> ValidationError | None: ...


class ParsedIdentifier:
    @property
    def birth_year(self) -> int: ...

    @property
    def birth_month(self) -> int: ...

    @property
    def birth_day(self) -> int: ...

    @property
    def gender(self) -> Literal["male", "female"] | None: ...


class Bech32Validation:
    @property
    def valid(self) -> bool: ...

    @property
    def code(self) -> Literal["format", "checksum", "component"] | None: ...


class ValidatorMetadata:
    @property
    def id(self) -> str: ...

    @property
    def name(self) -> str: ...

    @property
    def local_name(self) -> str: ...

    @property
    def abbreviation(self) -> str: ...

    @property
    def description(self) -> str | None: ...

    @property
    def aliases(self) -> list[str]: ...

    @property
    def candidate_pattern(self) -> str: ...

    @property
    def scope(self) -> ValidatorScope: ...

    @property
    def country(self) -> str | None: ...

    @property
    def entity_type(self) -> EntityType: ...

    @property
    def source_url(self) -> str | None: ...

    @property
    def lengths(self) -> list[int]: ...

    @property
    def examples(self) -> list[str]: ...

    @property
    def can_generate(self) -> bool: ...

    @property
    def can_parse(self) -> bool: ...


def validator_ids() -> list[str]: ...
def validators() -> list[ValidatorMetadata]: ...
def validator_metadata(id: str) -> ValidatorMetadata: ...
def validate(id: str, value: str) -> ValidationResult: ...
def compact(id: str, value: str) -> str: ...
def format(id: str, value: str) -> str: ...
def generate(id: str) -> str | None: ...
def parse(id: str, value: str) -> ParsedIdentifier | None: ...
def credit_card_detect_network(value: str) -> CardNetwork | None: ...
def eth_has_valid_eip55_checksum(value: str) -> bool: ...
def btc_base58_decode(value: str) -> bytes | None: ...
def btc_bech32_polymod(values: list[int]) -> int: ...
def btc_bech32_convert_bits(
    values: list[int], from_bits: int, to_bits: int
) -> list[int] | None: ...
def btc_bech32_validate(value: str) -> Bech32Validation: ...
def be_nn_checksum(value: str) -> int | None: ...
def es_vat_cif_checksum(value: str) -> int | None: ...
def ee_ik_two_pass_check(value: str) -> int | None: ...
def gb_nhs_calc_check_digit(value: str) -> int | None: ...
def gb_sedol_calc_check_digit(value: str) -> int | None: ...
def luhn_generate(length: int = 16) -> str: ...
def validate_id(validator: str, value: str, input: str | None = None) -> bool: ...
def validate_named_id(validator: str, value: str) -> bool: ...
