import { describe, expect, test } from "bun:test";

import {
  GENERATED_VERSION_METADATA,
  generatedVersionMetadataOnly,
} from "./changeset-policy";

const runtimePackageChangelogs = [
  "packages/stdnum/CHANGELOG.md",
  "packages/stdnum-wasm/CHANGELOG.md",
  "packages/stdnum-darwin-arm64/CHANGELOG.md",
  "packages/stdnum-darwin-x64/CHANGELOG.md",
  "packages/stdnum-linux-arm64-gnu/CHANGELOG.md",
  "packages/stdnum-linux-x64-gnu/CHANGELOG.md",
  "packages/stdnum-win32-x64-msvc/CHANGELOG.md",
];

describe("generated version metadata", () => {
  test("accepts every runtime package changelog generated by Changesets", () => {
    for (const changelog of runtimePackageChangelogs) {
      expect(
        GENERATED_VERSION_METADATA.has(changelog),
      ).toBe(true);
    }

    expect(
      generatedVersionMetadataOnly([
        ...runtimePackageChangelogs,
        "packages/stdnum/package.json",
        "Cargo.toml",
        "crates/stdnum-wasm-size-fixture/Cargo.lock",
        "VERSION",
        ".changeset/runtime-release.md",
      ]),
    ).toBe(true);
  });

  test("rejects changelogs outside the exact runtime package paths", () => {
    for (const changelog of [
      "packages/other/CHANGELOG.md",
      "packages/stdnum/docs/CHANGELOG.md",
      "packages/stdnum/CHANGELOG.next.md",
    ]) {
      expect(
        GENERATED_VERSION_METADATA.has(changelog),
      ).toBe(false);
      expect(
        generatedVersionMetadataOnly([changelog]),
      ).toBe(false);
    }
  });
});
