/**
 * Generate the binding-only TypeScript public surface from the committed
 * Rust registry snapshot.
 *
 * The normal path invokes the Rust registry exporter, making the core the
 * source of truth for runtime metadata and generated package entrypoints.
 *
 * Usage:
 *   bun scripts/generate-public-surface.ts
 *   bun scripts/generate-public-surface.ts --check
 */

import {
  mkdir,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";

type Scope = "country" | "global";
type EntityType = "person" | "company" | "any";
type ParseKind = "birthDate" | "person" | null;

type RegistryValidator = {
  abbreviation: string;
  aliases: string[];
  canGenerate: boolean;
  candidatePattern: string | null;
  country: string | null;
  description: string | null;
  entityType: EntityType;
  examples: string[];
  exportName: string;
  id: string;
  lengths: number[];
  localName: string;
  name: string;
  namedExports: string[];
  namespaceExport: string | null;
  parseKind: ParseKind;
  scope: Scope;
  sourceUrl: string | null;
  subpath: string;
};

type Registry = {
  $schema: string;
  schemaVersion: 1;
  validators: RegistryValidator[];
};

const ROOT = join(import.meta.dir, "..");
const PACKAGE_ROOT = join(ROOT, "packages", "stdnum");
const REGISTRY_PATH = join(PACKAGE_ROOT, "registry.json");
const README_PATH = join(ROOT, "README.md");
const TYPES_PATH = join(PACKAGE_ROOT, "src", "types.ts");
const PYTHON_STUB_PATH = join(
  ROOT,
  "crates",
  "stdnum-py",
  "python",
  "stella_stdnum",
  "_native.pyi",
);
const PYTHON_TYPES_PATH = join(
  ROOT,
  "crates",
  "stdnum-py",
  "python",
  "stella_stdnum",
  "_types.py",
);
const GENERATED_ROOT = join(
  PACKAGE_ROOT,
  "src",
  "generated",
);
const STANDARD_EXPORTS = new Set([
  "compact",
  "format",
  "generate",
  "parse",
  "validate",
]);

const validateRegistry = (value: unknown): Registry => {
  if (value === null || typeof value !== "object") {
    throw new Error("registry must be an object");
  }
  const registry = value as Partial<Registry>;
  if (
    registry.schemaVersion !== 1 ||
    !Array.isArray(registry.validators)
  ) {
    throw new Error(
      "unsupported or malformed registry schema",
    );
  }
  const ids = new Set<string>();
  const subpaths = new Set<string>();
  for (const validator of registry.validators) {
    if (
      !validator.id ||
      !validator.subpath ||
      !validator.exportName
    ) {
      throw new Error(
        "every registry validator needs id, subpath, and exportName",
      );
    }
    if (ids.has(validator.id))
      throw new Error(
        `duplicate validator id: ${validator.id}`,
      );
    if (subpaths.has(validator.subpath)) {
      throw new Error(
        `duplicate validator subpath: ${validator.subpath}`,
      );
    }
    ids.add(validator.id);
    subpaths.add(validator.subpath);
  }
  return registry as Registry;
};

const rustRegistry = async (): Promise<Registry> => {
  const exporter = Bun.spawn(
    [
      "cargo",
      "run",
      "--quiet",
      "--locked",
      "-p",
      "stella-stdnum-core",
      "--example",
      "export_registry",
    ],
    { cwd: ROOT, stdout: "pipe", stderr: "inherit" },
  );
  const output = await new Response(exporter.stdout).text();
  if ((await exporter.exited) !== 0)
    throw new Error("Rust registry exporter failed");
  return validateRegistry(JSON.parse(output));
};

const quote = (value: unknown): string =>
  JSON.stringify(value);
const generatedHeader =
  "// Generated by scripts/generate-public-surface.ts. Do not edit.\n";

const replaceDelimitedRegion = (
  document: string,
  begin: string,
  end: string,
  contents: string,
): string => {
  const start = document.indexOf(begin);
  const finish = document.indexOf(end);
  if (start < 0 || finish < start) {
    throw new Error(
      `generated region is missing: ${begin}`,
    );
  }
  return `${document.slice(0, start + begin.length)}\n${contents.trim()}\n${document.slice(finish)}`;
};

const replaceGeneratedRegion = (
  document: string,
  name: string,
  contents: string,
): string =>
  replaceDelimitedRegion(
    document,
    `<!-- BEGIN GENERATED: ${name} -->`,
    `<!-- END GENERATED: ${name} -->`,
    contents,
  );

const markdownTable = (
  headers: readonly string[],
  rows: readonly (readonly string[])[],
): string => {
  const widths = headers.map((header, index) =>
    Math.max(
      header.length,
      ...rows.map((row) => row.at(index)?.length ?? 0),
    ),
  );
  const row = (cells: readonly string[]): string =>
    `| ${cells
      .map((cell, index) =>
        cell.padEnd(widths.at(index) ?? cell.length),
      )
      .join(" | ")} |`;
  return [
    row(headers),
    row(widths.map((width) => "-".repeat(width))),
    ...rows.map(row),
  ].join("\n");
};

const readmeSupportedIdentifiers = (
  registry: Registry,
): string => {
  const globals = registry.validators.filter(
    (validator) => validator.scope === "global",
  );
  const countryValidators = registry.validators.filter(
    (validator) => validator.scope === "country",
  );
  const countries = new Set(
    countryValidators.map((validator) => validator.country),
  );
  const globalRows = globals.map((validator) => [
    validator.name,
    `\`${validator.subpath}\``,
    validator.entityType,
  ]);
  const countryRows: string[][] = [];
  let previousCountry: string | null = null;
  for (const validator of countryValidators) {
    const country = validator.country ?? "";
    const label =
      country === previousCountry ? "" : country;
    countryRows.push([
      label,
      `\`${validator.subpath}\``,
      validator.abbreviation,
    ]);
    previousCountry = country;
  }
  return `### International

${markdownTable(["Identifier", "Module", "Type"], globalRows)}

### Countries

<details>
<summary>${String(countries.size)} countries supported (click to expand)</summary>

${markdownTable(["Country", "Module", "Identifier"], countryRows)}

</details>`;
};

const writeReadme = async (
  registry: Registry,
): Promise<void> => {
  const globalCount = registry.validators.filter(
    (validator) => validator.scope === "global",
  ).length;
  const countryCount = new Set(
    registry.validators
      .filter((validator) => validator.scope === "country")
      .map((validator) => validator.country),
  ).size;
  let readme = await readFile(README_PATH, "utf8");
  readme = replaceGeneratedRegion(
    readme,
    "registry-summary",
    `This package covers ${String(globalCount)} global identifiers and ${String(countryCount)} countries through ${String(registry.validators.length)}\nper-module entry points.`,
  );
  readme = replaceGeneratedRegion(
    readme,
    "supported-identifiers",
    readmeSupportedIdentifiers(registry),
  );
  await writeFile(README_PATH, readme);
};

const validatorModule = (
  validator: RegistryValidator,
): string => {
  const depth = validator.subpath.split("/").length;
  const relative = "../".repeat(depth);
  const typeName =
    validator.scope === "country"
      ? `CountryValidator<${quote(validator.country)}${
          validator.parseKind === null
            ? ""
            : `, ${parseType(validator.parseKind)}`
        }>`
      : `GlobalValidator${
          validator.parseKind === null
            ? ""
            : `<${parseType(validator.parseKind)}>`
        }`;
  const imports =
    validator.scope === "country"
      ? "CountryValidator"
      : "GlobalValidator";
  const parsedImport =
    validator.parseKind === null
      ? ""
      : `, ${parseType(validator.parseKind)}`;
  const named = new Set(validator.namedExports);
  const hasSpecialExports =
    validator.namedExports.some(
      (name) =>
        !STANDARD_EXPORTS.has(name) &&
        name !== "CHECK_LETTERS",
    ) || validator.id === "luhn";
  const lines = [
    generatedHeader.trimEnd(),
    `import { createValidator${hasSpecialExports ? ", getBinding" : ""} } from ${quote(`${relative}runtime`)};`,
    `import type { ${imports}${parsedImport} } from ${quote(`${relative}types`)};`,
    "",
    `const ${validator.exportName}: ${typeName} = createValidator(${quote(validator.id)});`,
    "",
    `export default ${validator.exportName};`,
  ];

  for (const name of [
    "compact",
    "format",
    "validate",
    "generate",
    "parse",
  ]) {
    if (named.has(name)) {
      if (name === "generate") {
        lines.push(
          validator.id === "luhn"
            ? "export const generate = (length = 16): string => getBinding().luhnGenerate(length);"
            : `export const generate = (): string =>\n  ${validator.exportName}.generate?.() ??\n  (() => {\n    throw new Error(${quote(`Validator ${validator.id} cannot generate values`)});\n  })();`,
        );
      } else {
        lines.push(
          `export const ${name} = ${validator.exportName}.${name};`,
        );
      }
    }
  }
  if (validator.id === "creditcard") {
    lines.push(
      'export type CardNetwork = "visa" | "mastercard" | "amex" | "discover" | "diners" | "jcb" | "unionpay" | "maestro";',
    );
  }
  lines.push(...specialExports(validator));
  return `${lines.join("\n")}\n`;
};

const parseType = (
  kind: Exclude<ParseKind, null>,
): string =>
  kind === "person" ? "ParsedPersonId" : "ParsedBirthDate";

const specialExports = (
  validator: RegistryValidator,
): string[] => {
  const extras = validator.namedExports.filter(
    (name) => !STANDARD_EXPORTS.has(name),
  );
  if (extras.length === 0) return [];
  const lines: string[] = [];
  for (const name of extras) {
    if (
      validator.id === "es.dni" &&
      name === "CHECK_LETTERS"
    ) {
      lines.push(
        `export const CHECK_LETTERS = "TRWAGMYFPDXBNJZSQVHLCKE";`,
      );
      continue;
    }
    lines.push(specialFunction(validator.id, name));
  }
  return lines;
};

const specialFunction = (
  id: string,
  name: string,
): string => {
  const signatures: Record<string, string> = {
    "be.nn:checksum":
      "(value: string): number | null => getBinding().beNnChecksum(value)",
    "creditcard:detectNetwork":
      "(value: string): CardNetwork | null => getBinding().detectNetwork(value)",
    "crypto.btcbase58:decodeBase58":
      "(value: string): Uint8Array | null => getBinding().decodeBase58(value)",
    "crypto.btcbech32:convertBits":
      "(values: readonly number[], fromBits: number, toBits: number): number[] | null => getBinding().convertBits(values, fromBits, toBits)",
    "crypto.btcbech32:polymod":
      "(values: readonly number[]): number => getBinding().polymod(values)",
    "crypto.btcbech32:validateBech32":
      '(value: string): { valid: true } | { valid: false; code: "format" | "checksum" | "component" } => getBinding().validateBech32(value)',
    "crypto.eth:hasValidEip55Checksum":
      "(value: string): boolean => getBinding().hasValidEip55Checksum(value)",
    "ee.ik:twoPassCheck":
      "(digits: string): number => getBinding().eeIkTwoPassCheck(digits)",
    "es.vat:cifChecksum":
      "(digits: string): number => getBinding().esVatCifChecksum(digits)",
    "gb.nhs:calcCheckDigit":
      "(value: string): number | null => getBinding().gbNhsCalcCheckDigit(value)",
    "gb.sedol:calcCheckDigit":
      "(value: string): string => getBinding().gbSedolCalcCheckDigit(value)",
  };
  const signature = signatures[`${id}:${name}`];
  if (signature === undefined) {
    throw new Error(
      `unsupported legacy named export ${id}:${name}`,
    );
  }
  return `export const ${name} = ${signature};`;
};

const namespaceModule = (
  validators: RegistryValidator[],
): string => {
  const exports = validators
    .sort((left, right) =>
      left.exportName.localeCompare(right.exportName),
    )
    .map(
      (validator) =>
        `export { default as ${validator.exportName} } from ${quote(`./${validator.subpath.split("/").at(-1)}`)};`,
    );
  return `${generatedHeader}${exports.join("\n")}\n`;
};

const indexModule = (registry: Registry): string => {
  const globals = registry.validators.filter(
    (validator) => validator.namespaceExport === null,
  );
  const namespaces = [
    ...new Set(
      registry.validators
        .map((validator) => validator.namespaceExport)
        .filter((value): value is string => value !== null),
    ),
  ].sort();
  const lines = [
    generatedHeader.trimEnd(),
    `export type * from "../types";`,
    ...globals.map(
      (validator) =>
        `export { default as ${validator.exportName} } from ${quote(`./${validator.subpath}`)};`,
    ),
    ...namespaces.map((namespace) => {
      const directory = registry.validators
        .find(
          (validator) =>
            validator.namespaceExport === namespace,
        )
        ?.subpath.split("/")[0];
      return `export * as ${namespace} from ${quote(`./${directory}/mod`)};`;
    }),
  ];
  if (
    globals.some(
      (validator) => validator.id === "creditcard",
    )
  ) {
    lines.splice(
      3,
      0,
      `export { detectNetwork } from "./creditcard";`,
      `export type { CardNetwork } from "../types";`,
    );
  }
  return `${lines.join("\n")}\n`;
};

const registryModule = (registry: Registry): string => {
  const imports = registry.validators.map(
    (validator, index) =>
      `import v${index} from ${quote(`./${validator.subpath}`)};`,
  );
  return `${generatedHeader}${imports.join("\n")}\n\nexport const allValidators = [${registry.validators
    .map((_validator, index) => `v${index}`)
    .join(", ")}] as const;\n`;
};

const metadataModule = (registry: Registry): string =>
  `${generatedHeader}export const registryMetadata = ${JSON.stringify(
    registry.validators,
    null,
    2,
  )} as const;\n`;

const typeScriptUnion = (
  values: readonly string[],
): string =>
  values.map((value) => `  | ${quote(value)}`).join("\n");

const writeTypeScriptTypes = async (
  registry: Registry,
): Promise<void> => {
  const countries = [
    ...new Set(
      registry.validators
        .map((validator) => validator.country)
        .filter((value): value is string => value !== null),
    ),
  ].sort();
  const ids = registry.validators
    .map((validator) => validator.id)
    .sort();
  const generated = `export type CountryCode =\n${typeScriptUnion(countries)};\n\nexport type ValidatorId =\n${typeScriptUnion(ids)};`;
  const source = await readFile(TYPES_PATH, "utf8");
  await writeFile(
    TYPES_PATH,
    replaceDelimitedRegion(
      source,
      "// BEGIN GENERATED: registry-types",
      "// END GENERATED: registry-types",
      generated,
    ),
  );
};

const pythonLiteral = (values: readonly string[]): string =>
  values.map((value) => `    ${quote(value)},`).join("\n");

const pythonStub = (): string => {
  return `# Generated by scripts/generate-public-surface.ts. Do not edit.
from typing import Literal, final

from ._types import (
    CardNetwork as _CardNetwork,
    CountryCode as _CountryCode,
    EntityType as _EntityType,
    ErrorCode as _ErrorCode,
    ValidatorId as _ValidatorId,
    ValidatorScope as _ValidatorScope,
)

__all__: list[str]

@final
class ValidationError:
    @property
    def code(self) -> _ErrorCode: ...
    @property
    def message(self) -> str: ...

@final
class ValidationResult:
    @property
    def valid(self) -> bool: ...
    @property
    def compact(self) -> str | None: ...
    @property
    def error(self) -> ValidationError | None: ...

@final
class ParsedIdentifier:
    @property
    def birth_year(self) -> int: ...
    @property
    def birth_month(self) -> int: ...
    @property
    def birth_day(self) -> int: ...
    @property
    def gender(self) -> Literal["male", "female"] | None: ...

@final
class Bech32Validation:
    @property
    def valid(self) -> bool: ...
    @property
    def code(self) -> Literal["format", "checksum", "component"] | None: ...

@final
class ValidatorMetadata:
    @property
    def id(self) -> _ValidatorId: ...
    @property
    def name(self) -> str: ...
    @property
    def local_name(self) -> str: ...
    @property
    def abbreviation(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def aliases(self) -> list[str]: ...
    @property
    def candidate_pattern(self) -> str: ...
    @property
    def scope(self) -> _ValidatorScope: ...
    @property
    def country(self) -> _CountryCode | None: ...
    @property
    def entity_type(self) -> _EntityType: ...
    @property
    def source_url(self) -> str | None: ...
    @property
    def lengths(self) -> list[int]: ...
    @property
    def examples(self) -> list[str]: ...
    @property
    def can_generate(self) -> bool: ...
    @property
    def can_parse(self) -> bool: ...

def validator_ids() -> list[_ValidatorId]: ...
def validators() -> list[ValidatorMetadata]: ...
def validator_metadata(id: _ValidatorId) -> ValidatorMetadata: ...
def validate(id: _ValidatorId, value: str) -> ValidationResult: ...
def compact(id: _ValidatorId, value: str) -> str: ...
def format(id: _ValidatorId, value: str) -> str: ...
def generate(id: _ValidatorId) -> str | None: ...
def parse(id: _ValidatorId, value: str) -> ParsedIdentifier | None: ...
def credit_card_detect_network(value: str) -> _CardNetwork | None: ...
def eth_has_valid_eip55_checksum(value: str) -> bool: ...
def btc_base58_decode(value: str) -> bytes | None: ...
def btc_bech32_polymod(values: list[int]) -> int: ...
def btc_bech32_convert_bits(
    values: list[int], from_bits: int, to_bits: int
) -> list[int] | None: ...
def btc_bech32_validate(value: str) -> Bech32Validation: ...
def be_nn_checksum(value: str) -> int | None: ...
def es_vat_cif_checksum(value: str) -> int | None: ...
def ee_ik_two_pass_check(value: str) -> int | None: ...
def gb_nhs_calc_check_digit(value: str) -> int | None: ...
def gb_sedol_calc_check_digit(value: str) -> int | None: ...
def luhn_generate(length: int = 16) -> str: ...
def validate_id(validator: str, value: str, input: str | None = None) -> bool: ...
def validate_named_id(validator: str, value: str) -> bool: ...
`;
};

const pythonTypes = (registry: Registry): string => {
  const countries = [
    ...new Set(
      registry.validators
        .map((validator) => validator.country)
        .filter((value): value is string => value !== null),
    ),
  ].sort();
  const ids = registry.validators
    .map((validator) => validator.id)
    .sort();
  return `# Generated by scripts/generate-public-surface.ts. Do not edit.
from typing import Literal, TypeAlias

ValidatorId: TypeAlias = Literal[
${pythonLiteral(ids)}
]
CountryCode: TypeAlias = Literal[
${pythonLiteral(countries)}
]
ErrorCode: TypeAlias = Literal[
    "INVALID_FORMAT",
    "INVALID_LENGTH",
    "INVALID_CHECKSUM",
    "INVALID_COMPONENT",
]
EntityType: TypeAlias = Literal["person", "company", "any"]
ValidatorScope: TypeAlias = Literal["country", "global"]
CardNetwork: TypeAlias = Literal[
    "visa",
    "mastercard",
    "amex",
    "discover",
    "diners",
    "jcb",
    "unionpay",
    "maestro",
]

__all__ = [
    "CardNetwork",
    "CountryCode",
    "EntityType",
    "ErrorCode",
    "ValidatorId",
    "ValidatorScope",
]
`;
};

const conditionalExport = (output: string) => ({
  types: `./dist/${output}.d.ts`,
  import: `./dist/${output}.js`,
  default: `./dist/${output}.js`,
});

const writePackageExports = async (
  registry: Registry,
): Promise<void> => {
  const path = join(PACKAGE_ROOT, "package.json");
  const manifest = JSON.parse(
    await readFile(path, "utf8"),
  ) as Record<string, unknown>;
  const pinned = new Map<string, unknown>([
    [".", conditionalExport("index")],
    ["./types", conditionalExport("types")],
  ]);
  const rest = new Map<string, unknown>([
    ...registry.validators.map(
      (validator) =>
        [
          `./${validator.subpath}`,
          conditionalExport(validator.subpath),
        ] as const,
    ),
    ["./native", conditionalExport("native")],
    ["./native-node", conditionalExport("native-node")],
    ["./catalog", conditionalExport("catalog")],
    ["./patterns", conditionalExport("patterns")],
    ["./registry.json", "./registry.json"],
  ]);
  manifest.exports = Object.fromEntries([
    ...pinned,
    ...[...rest].sort(([left], [right]) =>
      left.localeCompare(right),
    ),
  ]);
  await writeFile(
    path,
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
};

const writeGenerated = async (
  registry: Registry,
): Promise<void> => {
  await rm(GENERATED_ROOT, {
    recursive: true,
    force: true,
  });
  for (const validator of registry.validators) {
    const path = join(
      GENERATED_ROOT,
      `${validator.subpath}.ts`,
    );
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, validatorModule(validator));
  }
  const grouped = Map.groupBy(
    registry.validators.filter(
      (validator) => validator.namespaceExport !== null,
    ),
    (validator) => validator.subpath.split("/")[0] ?? "",
  );
  for (const [directory, validators] of grouped) {
    await writeFile(
      join(GENERATED_ROOT, directory, "mod.ts"),
      namespaceModule(validators),
    );
  }
  await writeFile(
    join(GENERATED_ROOT, "index.ts"),
    indexModule(registry),
  );
  await writeFile(
    join(GENERATED_ROOT, "registry.ts"),
    registryModule(registry),
  );
  await writeFile(
    join(GENERATED_ROOT, "metadata.ts"),
    metadataModule(registry),
  );
  await writePackageExports(registry);
  await writeTypeScriptTypes(registry);
  await writeFile(PYTHON_STUB_PATH, pythonStub());
  await writeFile(PYTHON_TYPES_PATH, pythonTypes(registry));
  await writeReadme(registry);
  const formatter = Bun.spawn(
    [
      "bunx",
      "oxfmt",
      GENERATED_ROOT,
      join(PACKAGE_ROOT, "package.json"),
      TYPES_PATH,
      PYTHON_STUB_PATH,
      PYTHON_TYPES_PATH,
      REGISTRY_PATH,
      README_PATH,
    ],
    { cwd: ROOT, stdout: "ignore", stderr: "inherit" },
  );
  if ((await formatter.exited) !== 0)
    throw new Error("failed to format generated files");
};

const snapshotGenerated = async (): Promise<
  Map<string, string>
> => {
  const glob = new Bun.Glob("**/*.ts");
  const snapshot = new Map<string, string>();
  for await (const relative of glob.scan(GENERATED_ROOT)) {
    snapshot.set(
      relative,
      await readFile(
        join(GENERATED_ROOT, relative),
        "utf8",
      ),
    );
  }
  return snapshot;
};

const main = async (): Promise<void> => {
  const check = process.argv.includes("--check");
  const registry = await rustRegistry();
  if (!check) {
    await mkdir(PACKAGE_ROOT, { recursive: true });
    await writeFile(
      REGISTRY_PATH,
      `${JSON.stringify(registry, null, 2)}\n`,
    );
    await writeGenerated(registry);
    console.log(
      `Generated ${registry.validators.length} validator modules.`,
    );
    return;
  }
  const committedRegistry = validateRegistry(
    JSON.parse(await readFile(REGISTRY_PATH, "utf8")),
  );
  if (
    JSON.stringify(committedRegistry) !==
    JSON.stringify(registry)
  ) {
    throw new Error(
      "registry.json differs from the Rust registry exporter",
    );
  }
  const before = await snapshotGenerated();
  const manifestPath = join(PACKAGE_ROOT, "package.json");
  const manifestBefore = await readFile(
    manifestPath,
    "utf8",
  );
  const readmeBefore = await readFile(README_PATH, "utf8");
  const typesBefore = await readFile(TYPES_PATH, "utf8");
  const pythonStubBefore = await readFile(
    PYTHON_STUB_PATH,
    "utf8",
  );
  const pythonTypesBefore = await readFile(
    PYTHON_TYPES_PATH,
    "utf8",
  );
  await writeGenerated(registry);
  const after = await snapshotGenerated();
  const manifestAfter = await readFile(
    manifestPath,
    "utf8",
  );
  const readmeAfter = await readFile(README_PATH, "utf8");
  const typesAfter = await readFile(TYPES_PATH, "utf8");
  const pythonStubAfter = await readFile(
    PYTHON_STUB_PATH,
    "utf8",
  );
  const pythonTypesAfter = await readFile(
    PYTHON_TYPES_PATH,
    "utf8",
  );
  const unchanged =
    before.size === after.size &&
    manifestBefore === manifestAfter &&
    readmeBefore === readmeAfter &&
    typesBefore === typesAfter &&
    pythonStubBefore === pythonStubAfter &&
    pythonTypesBefore === pythonTypesAfter &&
    [...before].every(
      ([path, contents]) => after.get(path) === contents,
    );
  if (!unchanged) {
    const changedPaths = [
      ...(manifestBefore === manifestAfter
        ? []
        : ["packages/stdnum/package.json"]),
      ...(readmeBefore === readmeAfter
        ? []
        : ["README.md"]),
      ...(typesBefore === typesAfter
        ? []
        : ["packages/stdnum/src/types.ts"]),
      ...(pythonStubBefore === pythonStubAfter
        ? []
        : [
            "crates/stdnum-py/python/stella_stdnum/_native.pyi",
          ]),
      ...(pythonTypesBefore === pythonTypesAfter
        ? []
        : [
            "crates/stdnum-py/python/stella_stdnum/_types.py",
          ]),
      ...new Set([...before.keys(), ...after.keys()]),
    ]
      .filter(
        (path) =>
          !before.has(path) ||
          !after.has(path) ||
          before.get(path) !== after.get(path),
      )
      .sort();
    throw new Error(
      `generated public surface is out of date:\n${changedPaths.join("\n")}`,
    );
  }
  console.log(
    `Generated surface is current (${registry.validators.length} validators).`,
  );
};

await main();
